/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TricountsRouteImport } from './routes/tricounts'
import { Route as IndexRouteImport } from './routes/index'

const TricountsRoute = TricountsRouteImport.update({
  id: '/tricounts',
  path: '/tricounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tricounts': typeof TricountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tricounts': typeof TricountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tricounts': typeof TricountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tricounts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tricounts'
  id: '__root__' | '/' | '/tricounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TricountsRoute: typeof TricountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tricounts': {
      id: '/tricounts'
      path: '/tricounts'
      fullPath: '/tricounts'
      preLoaderRoute: typeof TricountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TricountsRoute: TricountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
